abstract: Low-level Lingr Chat API
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: WebService-Lingr
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Visitor::Callback: 0
  JSON::Syck: 0
  LWP: 0
  URI: 0
version: 0.02
